### ISSUE TITLE
[Feature] Suricata - Add payload support 

### ISSUE THREAD

**Issue by guillaume-u** [opnsense/core#1911]
Hello,

I think it's not already asked (I did not find this feature request).

Is it possible to add the payload support in "eve-log" and display the result in the WebUI ?

```
 - eve-log:
        - alert:
            payload: yes
            payload-buffer-size: 4kb
            payload-printable: yes
            packet: yes
```

It will be very useful to get this information to enable/disable/investigate Suricata rules.

Thanks,

Guillaume.
