### ISSUE TITLE
Unbound: sets forward-zone "." to system DNS

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#3044]
It seems with some of the last versions the unbound.conf gets a magic setting:

```
# Forwarding
forward-zone:
    name: "."
        forward-addr: <local resolver>

```
No idea if this was a changed introduced by unbound of OPNsense. But with this setting a forwarding option for BIND or DNSCrypt-Proxy is not usable anymore:

```
# Unbound custom options
do-not-query-localhost: no
forward-zone:
name: "."
forward-addr: 127.0.0.1@5353


# Forwarding
forward-zone:
    name: "."
        forward-addr: 1.1.1.1
```

From the logs:

`unbound: [34359:3] error: duplicate forward zone . ignored.`
