### ISSUE TITLE
syslog-ng destination with RFC5424

### ISSUE THREAD

**Issue by muuuh** [opnsense/core#4911]
Hello!

I've got a feature request concerning adding RFC5424 format to syslog-ng destinations config file.

**Issue:**
I've had a problem logging firewall-events to an Promtail / Loki / Grafana stack (which seems an alternative to ELK) via "syslog-ng". I've set up the syslog destination at "System: Settings: Logging / targets". With my tcp syslog destination (Promtail) for the Application "filter(filterlog)".
Promtail has currently this config:
```
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
    pipeline_stages:
#IPv4
    - match:
        selector: '{host="OPNsense.localdomain"}'
        stages:
        - regex:
            expression: '^(?P<rule_number>[\d]+),(?P<sub_rule_number>[\d]*),(?P<anchor>[\d]*),(?P<tracker>[\d]*),(?P<interface>[\w\d]*),(?P<reason>[\w]*),(?P<action>[\w]*),(?P<direction>[\w]*),(?P<ip_version>[\d]*),[x\da-f]*,[x\da-f]*,(?P<packet_ttl>[\d]*),(?P<packet_id>[\d]*),(?P<fragment_offset>[\w]*),(?P<ip_flags>.*?),(?P<protocol_id>[\d]*),(?P<protocol_name>[\w]*),(?P<source_port>[\d]*),(?P<source_ip>[\d.]*),(?P<dest_ip>[\d.]*),(?P<dest_port>[\d]*),'
        - labels:
            interface:
            action:
            direction:
            protocol_name:
            source_ip:
            source_port:
            dest_ip:
            dest_port:
```

Data is received, but I got the following error from Promtail:
`promtail_1  | level=warn ts=2021-04-10T15:55:49.704424007Z caller=syslogtarget.go:170 msg="error parsing syslog stream" err="expecting a version value in the range 1-999 [col 5]"`

**Problem**
Promtail seems to only accept RFC5424-format - https://grafana.com/docs/loki/latest/clients/promtail/scraping/#syslog-receiver

**Feature request**
It worked, after I manually patched /usr/local/etc/syslog-ng.conf.d/syslog-ng-destinations.conf to
```
### log target 9a54eada-9f88-49c6-9654-7e7e972b4250 : Docker Promtail ####
filter f_9a54eada9f8849c696547e7e972b4250_program {
    program("filterlog")
};

destination d_9a54eada9f8849c696547e7e972b4250 {
    network(
        "192.168.188.100"
        transport("tcp")
	flags(syslog-protocol)
        port(1514)
        ip-protocol(4)
        persist-name("9a54eada9f8849c696547e7e972b4250")
    );
};

log {
    source(s_all);
    filter(f_9a54eada9f8849c696547e7e972b4250_program);
    destination(d_9a54eada9f8849c696547e7e972b4250);
};
```

The added line is
`flags(syslog-protocol)`

After adding this line, the format was accepted by Promtail after I manually restarted the service with `service syslog-ng restart`. Of course this is only a temporary solution because this file will be re-written by the opnSense GUI.

Maybe this is a bug as https://forum.opnsense.org/index.php?topic=18314.0 already lists
`o system: syslog-ng RFC5424 on FreeBSD 12 needs flags(syslog-protocol)`

And there seems to be already a posting similar to this topic at https://github.com/opnsense/core/issues/4229#issuecomment-665651582

=> Maybe the line `flags(syslog-protocol)` could be added after https://github.com/opnsense/core/blob/af587e812a7b8d96cf3fd84869dc7e00bbfe09b3/src/opnsense/service/templates/OPNsense/Syslog/syslog-ng-destinations.conf#L28

Thank you and best regards,
