### ISSUE TITLE
It would be nice to add some popular DNS over TLS (DoT) resolvers with simple checkboxes

### ISSUE THREAD

**Issue by oittaa** [opnsense/core#5654]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is including your motivation for the request,
i.e. "For the purpose of [...] I am missing a solution that will [...]."

It would be great if you could enable DNS over TLS (and maybe DNS over HTTPS at some point) to popular public resolvers with simple checkboxes. That would avoid typos and silly mistakes that will happen every now and then while copy&pasting many ip addresses and domain names from the internet/etc.

**Describe the solution you like**

(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

For example Pi-hole has [a pretty decent UI](https://docs.pi-hole.net/guides/dns/cloudflared/#configuring-pi-hole) to enable popular DNS (although not over TLS) options. You just check if you want to use Google, Cloudflare, etc., and it just works. Maybe even simplify from that Pi-hole example and just have one checkbox per service and automatically add all IPv4 and IPv6 addresses depending if the protocols were supported via WAN. Maybe there's no harm in adding IPv6 forwarders even without IPv6 on WAN interface, but Opnsense is still pretty new to me so I'm not sure about that. 

Checking Cloudflare, Google, and Quad9 would add something like the following to unbound configuration.

```
forward-zone:
    name: "."
    forward-tls-upstream: yes

    ## Cloudflare
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
    forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
    forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

    ## Google
    forward-addr: 8.8.8.8@853#dns.google
    forward-addr: 8.8.4.4@853#dns.google
    forward-addr: 2001:4860:4860::8888@853#dns.google
    forward-addr: 2001:4860:4860::8844@853#dns.google

    ## Quad9
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net
    forward-addr: 2620:fe::fe@853#dns.quad9.net
    forward-addr: 2620:fe::9@853#dns.quad9.net

```

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or features you considered.

**Additional context**

Add any other context or screenshots about the feature request here or links to relevant forum thread or similar

Pi-hole UX is pretty good, but I think it could be even more simplified. Just one checkbox per popular DNS resolver.
![image](https://user-images.githubusercontent.com/8972248/160543292-12bdee68-8e19-4a5f-8446-514fb659b397.png)
