### ISSUE TITLE
Unbound blocklist (DNSBL) per interface

### ISSUE THREAD

**Issue by EdwinKM** [opnsense/core#5712]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I like to use Unbound for all my networks (to use static dns reservation). For some networks i want to use DNS filtering. AFAIK it is not possible to enable this per interface.

**Describe the solution you like**

Is it possible to add a dropdown at page "Services -> Unbound DNS -> Blocklist" with all networks?

**Describe alternatives you considered**

No alternatives

**Additional context**

Not applicable. First tried forum if i was missing a obvious feature (https://forum.opnsense.org/index.php?topic=27879.0). But unfortunally no replies.

**Comment by AdSchellevis** [comment]
I don't think it's (easily) possible with Unbound, ideas and implementation samples are welcome

**Comment by EdwinKM** [comment]
I think you are correct. Search of examples did reveal this is a general setting. Close the request as WONT_FIX?

**Comment by AdSchellevis** [comment]
I don't mind leaving it open for a while in case someone has ideas how to implement this. tickets will auto-close eventually.

**Comment by swhite2** [comment]
This is possible, but not obvious. See https://unix.stackexchange.com/questions/617091/can-you-specify-a-different-configuration-for-different-interfaces-in-unbound:

```
server:

    # Listen on two interfaces (or use 0.0.0.0 to listen on all):
    interface: 192.168.1.1   # LAN interface
    interface: 10.0.25.1     # Other interface

    # Define access controls
    access-control: 192.168.1.1/24 allow  # LAN interface
    access-control: 10.0.25.1/24 allow    # Other interface

    # Specify custom local answers for each interface by using views:
    access-control-view: 192.168.1.1/24 lan
    access-control-view: 10.0.25.1/24 other

    # Specify default local data:
    local-data: "common.example.com. 10800 IN A 12.34.56.78"

# Custom data for LAN interface
view:
    name: "lan"
    local-data: "common.example.com. 10800 IN A 192.168.1.1"

# Custom data for Other interface
view:
    name: "other"
    local-data: "common.example.com. 10800 IN A 10.0.25.1"
```

The blocklist configuration wouldn't be too difficult, but accounting for dynamic interface changes might be.
