### ISSUE TITLE
Unbound always uses DoT for Query Forwarding

### ISSUE THREAD

**Issue by definitio** [opnsense/core#5714]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

---

DoT always enabled when upstream servers are set in `Unbound DNS -> Query Forwarding`.

Generated config:
```
# Forward zones over TLS
server:
  tls-cert-bundle: /etc/ssl/cert.pem

forward-zone:
  name: "."
  forward-tls-upstream: yes
  forward-addr: 10.31.0.1@54
  forward-addr: 10.31.1.1@54
```

Nothing enabled in `Unbound DNS -> DNS over TLS` therefore it should be:
```
forward-zone:
  name: "."
  forward-addr: 10.31.0.1@54
  forward-addr: 10.31.1.1@54
```

**To Reproduce**

1. Go to 'Unbound DNS -> Query Forwarding'
2. Add DNS servers without DoT support
3. Apply settings
4. DNS resolution doesn't work

**Comment by fichtner** [comment]
Something is fishy, the “should be” includes “forward-tls-upstream: yes” which is likely wrong.

**Comment by definitio** [comment]
Sorry, you are right. Deleted line.

**Comment by AdSchellevis** [comment]
Can't reproduce either....

```
cat /usr/local/etc/unbound.opnsense.d/dot.conf 
server:
  do-not-query-localhost: no

# Forward zones
forward-zone:
  name: "opnsense.local"
  forward-addr: 127.0.0.1@654
forward-zone:
  name: "opnsense2.local"
  forward-addr: 127.0.0.2@654
```

**Comment by definitio** [comment]
There are same servers in `Services: Unbound DNS: DNS over TLS` as in `Services: Unbound DNS: Query Forwarding`. When a server enabled in `Services: Unbound DNS: Query Forwarding`, it's enabled in `Services: Unbound DNS: DNS over TLS` too. I can't disable DoT without disabling Query Forwarding.

**Comment by swhite2** [comment]
If you specify the same server in both Query Forwarding and DoT intentionally and enable them both, there are going to be two forward zones defined. How is Unbound supposed to know which one to pick? It simply picks the last one, which in our case is always DoT (the secure one). The Query Forwarding zone is going to be ignored. https://docs.opnsense.org/manual/unbound.html#dns-over-tls

**Comment by definitio** [comment]
I don't specify DoT servers.

**Comment by swhite2** [comment]
Can't reproduce it. Using only query forwarding:

```
root@OPNsense:/var/unbound/etc # cat dot.conf

# Forward zones
forward-zone:
  name: "."
  forward-addr: 1.1.1.1@53
  forward-addr: 8.8.8.8@53

```
