### ISSUE TITLE
Unbound DNS - Domain Override - Multiple entries for the same domain is not working.

### ISSUE THREAD

**Issue by reticulator** [opnsense/core#5748]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

In version 22.1.6 if you add multiple domain overrides for the same domain the `domainoverrides.conf` will contain the following.
```
forward-zone:
  name: "example.com"
  forward-addr: 192.168.0.11
forward-zone:
  name: "example.com"
  forward-addr: 192.168.0.12
```
After applying the configuration, the log will contain the following errors
```
2022-04-28T10:17:13-07:00 | Error | unbound | [31560:0] error: duplicate forward zone example.com. ignored.  
2022-04-28T10:17:13-07:00 | Error | unbound | [31560:1] error: duplicate forward zone example.com. ignored.
```

The only previous version I have available to test with is 22.1.2_2.  Adding the same domain overrides in this version yields the following in `domainoverrides.conf`.

```
forward-zone:
        name: "example.com"
        forward-addr: 192.168.0.11
        forward-addr: 192.168.0.12
```

**To Reproduce**

1. Go to Services -> Ubound DNS -> Overrides
2. Click on Domain Overrides
3. Add a new entry for "example.com", 192.168.0.11
3. Add a new entry for "example.com", 192.168.0.12
4. Click Apply
5. Go to Services -> Ubound DNS -> Log file
6. See error message in log.
7. SSH to firewall and launch the shell
8. Run `cat /usr/local/etc/unbound.opnsense.d/domainoverrides.conf`

**Expected behavior**

In `domainoverrides.conf`, multiple IP's for the same domain name should appear as additional forward-addr items under than same forward-zone entry for the domain.
```
forward-zone:
        name: "example.com"
        forward-addr: 192.168.0.11
        forward-addr: 192.168.0.12
```

**Additional context**

It appears some work was done between 22.1.2_2 and 22.1.6.  The old version had the host and domain overrides on the same page, and the new version has them split under separate table.  Also it appears the old version placed `domainoverrides.conf` in `/var/unbound/` and the new version places it under `/usr/local/etc/unbound.opnsense.d` which then gets copied to `/var/unbound/etc`.  Not sure how relevant this is but perhaps this bug was introduced when some of these changes were made.
