### ISSUE TITLE
Could we enable Suricata fast.log by default or give an option to enable?

### ISSUE THREAD

**Issue by j0nny55555** [opnsense/core#7083]
Acknowledging:

- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

For the purpose of easing parsing for CrowdSec and the Suricata Collection (https://app.crowdsec.net/hub/author/crowdsecurity/collections/suricata) that can be installed on OPNSense, I am missing a way to keep 'fast.log' enabled as CrowdSec has a very difficult time parsing the eve.json logs with the "printable_payload" details in the JSON. I do love that feature and track the logs in my ELK setup!! <3

**Describe the solution you like**

There would need to be a few changes:

1.
The /usr/local/etc/suricata/suricata.yaml would need the following configuration adopted and kept:
```
# Configure the type of alert (and other) logging you would like.               
outputs:                                                                        
                                                                                
  # a line based alerts log similar to Snort's fast.log                         
  - fast:                                                                       
      enabled: yes                                                              
      filename: fast.log                                                        
      append: yes                                                               
      #filetype: regular # 'regular', 'unix_stream' or 'unix_dgram' 
```
To note: Keep the eve.json - it is very helpful for ELK parsing, but CrowdSec doesn't handle the "printable_payload" parsing very well, so, the 'fast.log' is perfect for this!

2.
The log rotation would need to include the 'fast.log' element /etc/newsyslog.conf.d/suricata
```
# logfilename                   [owner:group]   mode    count   size    when    flags   [/pid_file]                             [sig_num]
/var/log/suricata/stats.log     root:wheel      640     7       *       $D0     BZ      /var/run/suricata.pid   1   
/var/log/suricata/fast.log      root:wheel      640     7       *       $D0     BZ      /var/run/suricata.pid   1   
/var/log/suricata/eve.json      root:wheel      640     1       500000  $W0D23  B       /var/run/suricata.pid   1 
```

There are likely a few places that reset the config from source, this will have to all be updated (in short, I can change the config file and when Suricata reloads its rules, the old config is re-applied). It would be nice if one could enable/disable this whole feature set, but, IMHO, fast.log is smaller than eve.json and ideally having both enabled should near be the same impact to disk/cpu.

**Describe alternatives you considered**

There is a chance to improve CrowdSec parsing of the EVE JSON logs, but, the 'printable_payload' often is not something to take lightly as far as parsing goes. It is a much better option to have CrowdSec use the fast.log output.

**Additional context**

Made a post very generally going over what I have done specifically to the OPNSense and Suricata and Newsyslog configs. I've already done some level of customization to OPNSense's CrowdSec install (Postgres the DB, put that the DB on an external host, keep the configs with the CrowdSec supported config.yaml.local feature <3 - now Mulit-Server with a fast DB via LAPI on OPNSense).
See here:
https://forum.opnsense.org/index.php?topic=37562.0

**Comment by AdSchellevis** [comment]
it would be more practical when CrowdSec would support eve.log to be honest, fast.log contains a limited set of the same data, not very fond of adding a duplicate.

**Comment by AdSchellevis** [comment]
(you can add it yourself though, see https://docs.opnsense.org/manual/ips.html#advanced-configuration)

**Comment by j0nny55555** [comment]
@AdSchellevis - thank you for the help! might need more...

it appears that I would be able to modify the /usr/local/opnsense/service/templates/OPNsense/IDS/custom.yaml file and add this to it?
```
# Configure the type of alert (and other) logging you would like.
outputs:
  # a line based alerts log similar to Snort's fast.log
  - fast:
      enabled: yes
      filename: fast.log
      append: yes
      #filetype: regular # 'regular', 'unix_stream' or 'unix_dgram'
```
That would effectively over-write the 'fast' element from the existing config/memory, or possibly more correctly, it would add a stanza to the in memory config, enabling 'fast.log' output (not looking to have to re-create the whole 'output' stanza, but if needed then that's what you do - though, if optimizations came/new suricata output config, in a package update, we wouldn't get it so I doubt that is how it works)?

In addition to that question about how the custom.yaml get integrated into the existing config(s):
How do I enable (and keep the config for) the log rotation of the new fast.log file in /etc/newsyslog/...?
