### ISSUE TITLE
Suricata dies every 16-18h due to "failed to reclaim memory" (in 16GB RAM machine)

### ISSUE THREAD

**Issue by githstl** [opnsense/core#8357]
**Describe the bug**

Suricata proces dies every 16-18h due to "failed to reclaim memory"

**To Reproduce**

1. subscribe to ET Pro telemetry
2. enable ET Pro telemetry rules
3. Enable IDS (in IDS mode or IPS - it doesn't matter)
4. set update rules to 3-4 hours
5. apply two policies: First - change Alert to Drop for emerged-exploit,ftp,malware,phishing rules. Second - change Alert to Drop for activities: attempt-admin, dos,recon etc for Critial, Major and Minor signature_severity
6. wait

**Expected behavior**

Stay alive, not consuming all memory

**Describe alternatives you considered**

Tried workarounds like this - not helped:
```
    smb:
      enabled: yes
      detection-ports:
        dp: 139, 445

      # Stream reassembly size for SMB streams. By default track it completely.
      # limited to avoid memory exhaustion
      stream-depth: 32mb
```

**Relevant log files**

```
<13>1 2025-02-19T18:13:05+01:00 OPNs1.xyx.com rule-updater.py 77453 - [meta sequenceId="53"] download skipped emerging-web_server.rules, same version
<13>1 2025-02-19T18:13:05+01:00 OPNs1.xyx.com rule-updater.py 77453 - [meta sequenceId="54"] download skipped emerging-web_specific_apps.rules, same version
<13>1 2025-02-19T18:13:05+01:00 OPNs1.xyx.com rule-updater.py 77453 - [meta sequenceId="55"] download skipped emerging-worm.rules, same version
<13>1 2025-02-19T18:51:03+01:00 OPNs1.xyx.com kernel - - [meta sequenceId="1"] <3>pid 70333 (suricata), jid 0, uid 0, was killed: failed to reclaim memory
```

**Additional context**

Has to run now in IDS mode, because when Suricata dies in IPS mode - it disrupt traffic heavily.
Cron task restarts Suricata every 6h

OPNsense "see" traffic from 120pcs, about 40-50Mbps.

**Environment**

OPNsense 25.1.1-amd64, 16GB RAM.
Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
I350 Gigabit Fiber Network Connection
I211 Gigabit Network Connection
